name: Deploy Storybook to S3
on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run deployment script
        run: ./scripts-old/deploy-storybook-to-s3.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STORYBOOK_UPDATER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STORYBOOK_UPDATER_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          S3_BUCKET_NAME: storybook.mlmodelscope.org
